### ISSUE TITLE
Docs - add technical description of algorithms

### ISSUE THREAD

**Issue by agerada** [agerada/AIgarMIC#11]
Add new page to documentation to provide technical description of the following algorithms used within `AIgarMIC`:

- [x] grid splitting
- [x]  MIC calculation
- [x]  QC control algorithm

**Comment by agerada** [comment]
Added new documentation [page](https://aigarmic.readthedocs.io/en/latest/technical.html#technical-background) to give explanation of original alogirthms used in `AIgarMIC`. 

See #15

Tagging @gchure for review - thank you. 

I will also run through the pseudo-code again to make sure correct.

**Comment by gchure** [comment]
Thanks for adding this. I want to make sure I understand something correctly with the MIC -- in AIgarMIC, the MIC must be one of the concentrations used in the original screen, correct? Looking through things, I can't find a specific model that you are fitting -- rather, you're iterating through concentrations until you find one where the growth is inhibited.

**Comment by agerada** [comment]
Yes that's right – the MIC can only be one of the `Plate` concentrations entered into the `PlateSet`. I think it will be interesting in future work to explore models that could perhaps calculate the MIC based on the image data provided (but without the MIC algorithm described here). In theory this could perhaps increase the resolution of the MIC (e.g., reporting between two measured concentrations) if a model is developed that demonstrates a relationship between the type of growth inhibition (e.g., faint film, single small colony, multiple small colonies), and MIC as measured by another method (broth microdilution).

**Comment by gchure** [comment]
Okay, just wanted to make sure I was understanding it correctly. Great job on the documentation!
